"""affiliate program

Revision ID: 4fb2ceabcadf
Revises: c8a41d27f5b9
Create Date: 2026-08-07 13:33:32.701306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb2ceabcadf'
down_revision = 'c8a41d27f5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_program_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_commission_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('interest_type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('referral_code_used', sa.String(length=12), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("interest_type in ('grow_existing_channel','grow_from_scratch','buy_channel','master_class')", name='ck_prospect_interest_type'),
    sa.CheckConstraint("status in ('new','contacted','converted','lost')", name='ck_prospect_status'),
    sa.ForeignKeyConstraint(['affiliate_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prospects_affiliate_id'), ['affiliate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_email'), ['email'], unique=False)

    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_percent_snapshot', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pending','approved','paid','voided')", name='ck_commission_status'),
    sa.ForeignKeyConstraint(['affiliate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commissions_affiliate_id'), ['affiliate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commissions_prospect_id'), ['prospect_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('commission_rate_percent', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)
        # autogenerate doesn't diff CHECK constraints (SQLite reflection
        # doesn't expose them) — added by hand to include the new 'affiliate'
        # role.
        batch_op.drop_constraint('ck_users_role', type_='check')
        batch_op.create_check_constraint(
            'ck_users_role', "role in ('admin','clipper','producer','affiliate')"
        )

    # Seed the singleton settings row so AffiliateProgramSettings.get()'s
    # defensive get-or-create path is never exercised in normal operation.
    affiliate_program_settings = sa.table(
        'affiliate_program_settings',
        sa.column('id', sa.Integer),
        sa.column('default_commission_rate_percent', sa.Numeric),
    )
    op.bulk_insert(
        affiliate_program_settings,
        [{'id': 1, 'default_commission_rate_percent': 10.00}],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # affiliate-role accounts can't survive the downgrade — the 3-role
    # constraint being restored below would reject them.
    op.execute("DELETE FROM users WHERE role = 'affiliate'")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_users_role', type_='check')
        batch_op.create_check_constraint(
            'ck_users_role', "role in ('admin','clipper','producer')"
        )
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_column('commission_rate_percent')
        batch_op.drop_column('referral_code')

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commissions_prospect_id'))
        batch_op.drop_index(batch_op.f('ix_commissions_created_at'))
        batch_op.drop_index(batch_op.f('ix_commissions_affiliate_id'))

    op.drop_table('commissions')
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prospects_email'))
        batch_op.drop_index(batch_op.f('ix_prospects_created_at'))
        batch_op.drop_index(batch_op.f('ix_prospects_affiliate_id'))

    op.drop_table('prospects')
    op.drop_table('affiliate_program_settings')
    # ### end Alembic commands ###
