"""master class enrollment

Revision ID: 835c9817ece0
Revises: 4fb2ceabcadf
Create Date: 2026-08-07 14:14:52.469845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835c9817ece0'
down_revision = '4fb2ceabcadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_class_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_open_for_enrollment', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_class_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=False),
    sa.Column('buyer_email', sa.String(length=255), nullable=False),
    sa.Column('buyer_phone', sa.String(length=50), nullable=True),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('affiliate_id', sa.Integer(), nullable=True),
    sa.Column('referral_code_used', sa.String(length=12), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paystack_reference', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pending','paid','failed','refunded')", name='ck_enrollment_status'),
    sa.ForeignKeyConstraint(['affiliate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_class_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_class_enrollments_affiliate_id'), ['affiliate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_class_enrollments_buyer_email'), ['buyer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_class_enrollments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_class_enrollments_paystack_reference'), ['paystack_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_master_class_enrollments_prospect_id'), ['prospect_id'], unique=False)

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_enrollment_id', sa.Integer(), nullable=True))
        batch_op.alter_column('created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(
            'uq_commissions_source_enrollment_id', ['source_enrollment_id']
        )
        batch_op.create_foreign_key(
            'fk_commissions_source_enrollment_id',
            'master_class_enrollments', ['source_enrollment_id'], ['id'],
        )

    # Seed the singleton settings row, same reasoning as
    # affiliate_program_settings in the previous migration — keeps
    # MasterClassSettings.get()'s defensive get-or-create path from firing
    # in normal operation. is_open_for_enrollment stays False (the model
    # default) until an admin explicitly opens it.
    master_class_settings = sa.table(
        'master_class_settings',
        sa.column('id', sa.Integer),
        sa.column('price_amount', sa.Numeric),
        sa.column('currency', sa.String),
        sa.column('is_open_for_enrollment', sa.Boolean),
    )
    op.bulk_insert(
        master_class_settings,
        [{'id': 1, 'price_amount': 50000.00, 'currency': 'NGN', 'is_open_for_enrollment': False}],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Auto-created commissions (webhook-paid Master Class enrollments) have
    # no admin creator — same "can't satisfy the constraint being restored"
    # situation as c8a41d27f5b9's downgrade, handled the same way.
    op.execute("DELETE FROM commissions WHERE created_by_id IS NULL")

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_commissions_source_enrollment_id', type_='foreignkey')
        batch_op.drop_constraint('uq_commissions_source_enrollment_id', type_='unique')
        batch_op.alter_column('created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('source_enrollment_id')

    with op.batch_alter_table('master_class_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_class_enrollments_prospect_id'))
        batch_op.drop_index(batch_op.f('ix_master_class_enrollments_paystack_reference'))
        batch_op.drop_index(batch_op.f('ix_master_class_enrollments_created_at'))
        batch_op.drop_index(batch_op.f('ix_master_class_enrollments_buyer_email'))
        batch_op.drop_index(batch_op.f('ix_master_class_enrollments_affiliate_id'))

    op.drop_table('master_class_enrollments')
    op.drop_table('master_class_settings')
    # ### end Alembic commands ###
