"""initial schema

Revision ID: 9301f7e03092
Revises: 
Create Date: 2026-07-12 13:04:35.203526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9301f7e03092'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('applies_to_role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("applies_to_role is null or applies_to_role in ('clipper','producer')", name='ck_metric_applies_to_role'),
    sa.CheckConstraint("data_type in ('integer','float','boolean','duration_seconds')", name='ck_metric_data_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role in ('admin','clipper','producer')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('connected_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('token_blob', sa.Text(), nullable=True),
    sa.Column('scopes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("provider in ('youtube','tiktok','google_drive')", name='ck_channels_provider'),
    sa.CheckConstraint("status in ('connected','disconnected','error')", name='ck_channels_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'channel_id', name='uq_channel_per_user')
    )
    with op.batch_alter_table('connected_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connected_channels_user_id'), ['user_id'], unique=False)

    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('geo_country', sa.String(length=120), nullable=True),
    sa.Column('geo_region', sa.String(length=120), nullable=True),
    sa.Column('geo_city', sa.String(length=120), nullable=True),
    sa.Column('geo_lat', sa.Numeric(), nullable=True),
    sa.Column('geo_lon', sa.Numeric(), nullable=True),
    sa.Column('geo_raw', sa.JSON(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_user_id'), ['user_id'], unique=False)

    op.create_table('metric_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_events_user_id'), ['user_id'], unique=False)

    op.create_table('reward_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('threshold_low', sa.Numeric(), nullable=True),
    sa.Column('threshold_high', sa.Numeric(), nullable=True),
    sa.Column('reward_description', sa.Text(), nullable=True),
    sa.Column('applies_to_role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("applies_to_role is null or applies_to_role in ('clipper','producer')", name='ck_reward_applies_to_role'),
    sa.CheckConstraint("operator in ('gte','lte','eq','between')", name='ck_reward_operator'),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reward_rules')
    with op.batch_alter_table('metric_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_metric_events_occurred_at'))

    op.drop_table('metric_events')
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_events_created_at'))

    op.drop_table('login_events')
    with op.batch_alter_table('connected_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connected_channels_user_id'))

    op.drop_table('connected_channels')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('metric_definitions')
    # ### end Alembic commands ###
