"""add watched channels, discovered videos, suggested clips

Revision ID: e441130b504a
Revises: 9301f7e03092
Create Date: 2026-07-15 08:48:29.118342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e441130b504a'
down_revision = '9301f7e03092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_url', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('platform_target', sa.String(length=30), nullable=True),
    sa.Column('added_by_user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("platform_target is null or platform_target in ('TikTok','Shorts','Reels','Twitter/X','LinkedIn')", name='ck_watched_channel_platform'),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovered_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_watch_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('video_title', sa.String(length=500), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('process_status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("process_status in ('pending','no_transcript','suggested','error')", name='ck_discovered_video_status'),
    sa.ForeignKeyConstraint(['channel_watch_id'], ['watched_channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_watch_id', 'video_url', name='uq_video_per_channel')
    )
    with op.batch_alter_table('discovered_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_videos_channel_watch_id'), ['channel_watch_id'], unique=False)

    op.create_table('suggested_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discovered_video_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pending','approved','rejected')", name='ck_suggested_clip_status'),
    sa.ForeignKeyConstraint(['discovered_video_id'], ['discovered_videos.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggested_clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggested_clips_discovered_video_id'), ['discovered_video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggested_clips_discovered_video_id'))

    op.drop_table('suggested_clips')
    with op.batch_alter_table('discovered_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_videos_channel_watch_id'))

    op.drop_table('discovered_videos')
    op.drop_table('watched_channels')
    # ### end Alembic commands ###
