"""channel marketplace

Revision ID: ed23b411fb01
Revises: 835c9817ece0
Create Date: 2026-08-07 18:23:14.085267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed23b411fb01'
down_revision = '835c9817ece0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('niche', sa.String(length=100), nullable=True),
    sa.Column('monetization_status', sa.String(length=20), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('stats_note', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('holder_order_id', sa.Integer(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("availability in ('available','reserved','sold')", name='ck_listing_availability'),
    sa.CheckConstraint("monetization_status in ('monetized','unmonetized')", name='ck_listing_monetization_status'),
    sa.CheckConstraint("status in ('draft','published','withdrawn')", name='ck_listing_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_listings_created_at'), ['created_at'], unique=False)

    op.create_table('channel_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=False),
    sa.Column('buyer_email', sa.String(length=255), nullable=False),
    sa.Column('buyer_phone', sa.String(length=50), nullable=True),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('affiliate_id', sa.Integer(), nullable=True),
    sa.Column('referral_code_used', sa.String(length=12), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paystack_reference', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pending','failed','paid','payment_conflict','handoff_in_progress','completed','refunded','cancelled')", name='ck_order_status'),
    sa.ForeignKeyConstraint(['affiliate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['channel_listings.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_orders_affiliate_id'), ['affiliate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_orders_buyer_email'), ['buyer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_orders_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_orders_paystack_reference'), ['paystack_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_channel_orders_prospect_id'), ['prospect_id'], unique=False)

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_order_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_commissions_source_order_id', ['source_order_id'])
        batch_op.create_foreign_key(
            'fk_commissions_source_order_id', 'channel_orders', ['source_order_id'], ['id']
        )
        batch_op.create_check_constraint(
            'ck_commission_single_source', 'source_enrollment_id is null or source_order_id is null'
        )

    # holder_order_id -> channel_orders.id: not declared as a SQLAlchemy FK
    # on the model (channel_orders didn't exist yet when channel_listings
    # is created above — mutually referential tables), added by hand here,
    # same technique as 835c9817ece0's source_enrollment_id addition.
    with op.batch_alter_table('channel_listings', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_channel_listings_holder_order_id', 'channel_orders', ['holder_order_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_listings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_channel_listings_holder_order_id', type_='foreignkey')

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_constraint('ck_commission_single_source', type_='check')
        batch_op.drop_constraint('fk_commissions_source_order_id', type_='foreignkey')
        batch_op.drop_constraint('uq_commissions_source_order_id', type_='unique')
        batch_op.drop_column('source_order_id')

    with op.batch_alter_table('channel_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_orders_prospect_id'))
        batch_op.drop_index(batch_op.f('ix_channel_orders_paystack_reference'))
        batch_op.drop_index(batch_op.f('ix_channel_orders_listing_id'))
        batch_op.drop_index(batch_op.f('ix_channel_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_channel_orders_buyer_email'))
        batch_op.drop_index(batch_op.f('ix_channel_orders_affiliate_id'))

    op.drop_table('channel_orders')
    with op.batch_alter_table('channel_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_listings_created_at'))

    op.drop_table('channel_listings')
    # ### end Alembic commands ###
