"""listing attachments

Revision ID: fc3bf5a9a5c6
Revises: ed23b411fb01
Create Date: 2026-08-08 01:55:44.178946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3bf5a9a5c6'
down_revision = 'ed23b411fb01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=150), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['channel_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    with op.batch_alter_table('listing_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_attachments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_attachments_listing_id'), ['listing_id'], unique=False)

    # NOTE: autogenerate also proposed dropping
    # fk_channel_listings_holder_order_id here — a false positive. The
    # ChannelListing model deliberately never declares holder_order_id as a
    # db.ForeignKey in Python (channel_orders doesn't exist yet at the point
    # channel_listings is created in migration ed23b411fb01 — see that
    # model's own comment), so autogenerate's model-vs-DB diff sees the
    # real DB constraint as something the model "removed." Dropping it
    # would break the marketplace's two-stage locking. Left untouched.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_attachments_listing_id'))
        batch_op.drop_index(batch_op.f('ix_listing_attachments_created_at'))

    op.drop_table('listing_attachments')
    # ### end Alembic commands ###
