from datetime import datetime, timezone

from ..extensions import db

ENROLLMENT_STATUSES = ("pending", "paid", "failed", "refunded")


class MasterClassEnrollment(db.Model):
    """A Paystack-backed purchase of the 0->1k Master Class. Guest
    checkout — no account required, same as Prospect/the homepage's
    /interest capture. amount is a frozen snapshot of MasterClassSettings'
    price at enroll time, so a later price change never rewrites history.
    """

    __tablename__ = "master_class_enrollments"

    id = db.Column(db.Integer, primary_key=True)
    buyer_name = db.Column(db.String(200), nullable=False)
    buyer_email = db.Column(db.String(255), nullable=False, index=True)
    buyer_phone = db.Column(db.String(50))
    prospect_id = db.Column(db.Integer, db.ForeignKey("prospects.id"), index=True)
    affiliate_id = db.Column(db.Integer, db.ForeignKey("users.id"), index=True)
    referral_code_used = db.Column(db.String(12))
    amount = db.Column(db.Numeric(10, 2), nullable=False)
    currency = db.Column(db.String(3), nullable=False, default="NGN")
    # Generated by us (not Paystack) before the redirect, so it's the known
    # join key the callback/webhook look enrollments up by.
    paystack_reference = db.Column(db.String(100), nullable=False, unique=True, index=True)
    status = db.Column(db.String(20), nullable=False, default="pending")
    paid_at = db.Column(db.DateTime(timezone=True))
    ip_address = db.Column(db.String(64))
    created_at = db.Column(
        db.DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True
    )
    updated_at = db.Column(
        db.DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    prospect = db.relationship("Prospect", foreign_keys=[prospect_id])
    affiliate = db.relationship("User", foreign_keys=[affiliate_id])

    __table_args__ = (
        db.CheckConstraint(
            "status in ('pending','paid','failed','refunded')", name="ck_enrollment_status"
        ),
    )


class MasterClassSettings(db.Model):
    """Singleton row (id=1). is_open_for_enrollment defaults False so the
    checkout flow stays closed until an admin has actually configured
    Paystack keys and a real price.
    """

    __tablename__ = "master_class_settings"

    id = db.Column(db.Integer, primary_key=True)
    price_amount = db.Column(db.Numeric(10, 2), nullable=False, default=50000)
    currency = db.Column(db.String(3), nullable=False, default="NGN")
    is_open_for_enrollment = db.Column(db.Boolean, nullable=False, default=False)
    updated_at = db.Column(
        db.DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    @classmethod
    def get(cls):
        row = cls.query.get(1)
        if row is None:
            row = cls(id=1, price_amount=50000, currency="NGN", is_open_for_enrollment=False)
            db.session.add(row)
            db.session.commit()
        return row
